Make recipient notes response field optional
chewse/python-onfleet pull request #10
Opened 2016-11-03 17:17 UTC by OneRedOak

Stemming from our findings about Onfleet in chewse/chewse/issues/2337, we need to make the `recipient`'s `notes` field option when parsing responses, given that the field may sometimes be absent entirely.

This will fix issue chewse/chewse/issues/2341

2016-11-03 17:59 UTC, jpulec requested changes

2016-11-03 17:59 UTC, jpulec commented on onfleet/models.py
>              notes=obj['notes']
You will still need to remove this line.

2016-11-03 18:05 UTC, OneRedOak commented on onfleet/models.py
>              notes=obj['notes']
Yikes -- thanks for catching that.

2016-11-03 18:07 UTC, OneRedOak commented
@jpulec Just made the requested change.

2016-11-04 23:37 UTC, jpulec approved these changes

2016-11-04 23:38 UTC, merged