Add support for Onfleet Containers
chewse/python-onfleet pull request #8
Opened 2016-10-19 02:41 UTC by OneRedOak

Adds support to python-onfleet for: http://docs.onfleet.com/docs/containers

With these changes, we can parse responses from container calls (even though nothing is returned).

And example call using this from chewse/chewse would include: 
```
onfleet_api.containers.workers[self.onfleet_worker_id](
    {'tasks': [-1] + task_ids},
    method='PUT'
)
```

2016-10-19 23:36 UTC, jpulec requested changes
After looking at onfleets docs and this PR, I don't really think its necessary. Adding a container class does nothing for us.

2016-10-19 23:36 UTC, jpulec commented on onfleet/models.py
> +class Container(object):
After looking at onfleet's api again, and how it is inconsistent for containers.. I don't think this is worth doing at all. It doesn't do anything for us.

2016-10-25 00:34 UTC, OneRedOak commented
@jpulec Changes have been made - ready for a re-review.

2016-10-25 01:43 UTC, jpulec approved these changes
LGTM

2016-10-31 00:52 UTC, merged